# Generated by Django 5.1.1 on 2024-09-17 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(default='HomeHive', max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('total_number_of_houses', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('available_houses', models.PositiveIntegerField()),
            ],
        ),
    ]
