# Generated by Django 5.1.1 on 2024-09-17 05:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='Properties.amenity'),
        ),
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid phone number format (XXX-XXX-XXXX)', regex='\\d{10}')])),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caretaker', to='Properties.building')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('house_number', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid phone number format (XXX-XXX-XXXX)', regex='\\d{10}')])),
                ('number_of_rooms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_people', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='Properties.building')),
            ],
        ),
        migrations.CreateModel(
            name='TotalTenants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Properties.building')),
            ],
        ),
    ]
